package at.fhj.ima.facilitron.model

import jakarta.persistence.*

/**
 * Base Class for all departments
 * @author SJB
 * @param id is AutoGenerated.
 * @param name is the name of the department
 * @param description is the description of the department
 * @param head is the head of department
 */
@Entity
class Department (
    @Id @GeneratedValue(strategy = GenerationType.AUTO)
    val id:Int? = null,
    val name:String,
    val description:String,
    @OneToOne(fetch = FetchType.EAGER)
    val head:Employee
)