package at.fhj.ima.facilitron.model

import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Index
import org.springframework.security.core.GrantedAuthority
import org.springframework.security.core.authority.SimpleGrantedAuthority
import org.springframework.security.core.userdetails.UserDetails

/**
 * Base Class for all users
 * @author TK Inc.
 * @param id is AutoGenerated
 * @param firstName
 * @param secondName
 * @param phone
 * @param mail is used as Username
 * @param accountStatus information about employee status
 * @param roles contains access authority of user
 */
@Entity
class Employee(
    @Id @GeneratedValue(strategy = GenerationType.AUTO)
    val id:Int? = null,
    private val firstName:String,
    private val secondName:String,
    private val mail:String,
    private val password:String,
    private val phone:String? = null,
    private val accountStatus:AccountStatus = AccountStatus.ACTIVE,
    private val roles:MutableList<Role> = mutableListOf(Role.EMPLOYEE),
) : UserDetails {
    override fun getAuthorities(): MutableCollection<out GrantedAuthority> {
        return roles.map { SimpleGrantedAuthority(it.name) } as MutableList<out GrantedAuthority>
    }

    fun addAuthority(role:Role){
        roles.add(role)
    }

    override fun getPassword(): String {
        return password
    }

    override fun getUsername(): String {
        return mail
    }

    override fun isAccountNonExpired(): Boolean {
        return true
    }

    override fun isAccountNonLocked(): Boolean {
        return accountStatus != AccountStatus.LOCKED
    }

    override fun isCredentialsNonExpired(): Boolean {
        return true
    }

    override fun isEnabled(): Boolean {
        return accountStatus == AccountStatus.ACTIVE
    }

}