package at.fhj.ima.facilitron.model

import jakarta.persistence.*
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.temporal.ChronoUnit
import java.util.Date

/**
 * Base class for all occupations
 * @author SJB
 * @param id is AutoGenerated
 * @param type --> Arrival or Departure
 * @param arrivalTime start working time
 * @param departureTime end working time
 * @param workload only available after departure
 * @param employee link to the employee
 */

@Entity
class Ocupation (
    @Id @GeneratedValue(strategy = GenerationType.AUTO)
    val id:Int? = null,
    var type:OcupationType? = null,
    val arrivalTime: LocalDateTime = LocalDateTime.now(),
    var departureTime:LocalDateTime? = null,
    var workload:String? = null,
    @ManyToOne
    val employee: Employee
) {
    fun getDate():LocalDate{
        return arrivalTime.toLocalDate()
    }

    fun getArrivalTimeSeconds(): LocalTime {
        return arrivalTime.toLocalTime().truncatedTo(ChronoUnit.SECONDS)
    }

    fun getDepartureTimeSeconds(): LocalTime? {
        return departureTime?.toLocalTime()?.truncatedTo(ChronoUnit.SECONDS)
    }
}