package at.fhj.ima.facilitron.model

import jakarta.persistence.*
import java.time.LocalDateTime

/**
 * Base Class for all ticket-comments
 * @author SJB
 * @param id is AutoGenerated.
 * @param comment is the actual comment text
 * @param commenter is the employee who wrote the comment
 * @param postedTime is the time the comment was posted
 * @param ticket is the link to the ticket
 */
@Entity
class TicketComment (
    @Id @GeneratedValue(strategy = GenerationType.AUTO)
    val id:Int? = null,
    val comment:String,
    @ManyToOne
    val commenter:Employee,
    val postedTime: LocalDateTime = LocalDateTime.now(),
    @ManyToOne
    val ticket:Ticket
)